import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
const html=read("public/index.html");
const runtime=read("public/runtime-v14.js");
const avatarRuntime=read("public/avatar-runtime-v15.js");
const resetRuntime=read("public/reset-runtime-v16.js");
const visualRuntime=read("public/visual-runtime-v17.js");
const roomRuntime=read("public/room-runtime-v19.js");
const poseRuntime=read("public/pose-runtime-v20.js");
const coreRuntime=read("public/core-runtime-v21.js");
const continuityRuntime=read("public/continuity-runtime-v22.js");
const cinemaRuntime=read("public/cinema-runtime-v23.js");
const cinemaBackgroundClient=read("public/cinema-background-v23.js");
const motionRuntime=read("public/motion-runtime-v26.js");
const worker=read("src/index.js");
const life=read("src/life-engine.js");
const visual=read("src/visual-engine.js");
const cinema=read("src/cinema-engine.js");
const cinemaBackground=read("src/cinema-background.js");
const sql1=read("migrations/0001_init.sql");
const sql2=read("migrations/0002_auth_and_risk.sql");
const sql3=read("migrations/0003_life_engine.sql");
const manifest=JSON.parse(read("public/manifest.webmanifest"));
const sw=read("public/sw.js");
const wrangler=JSON.parse(read("wrangler.jsonc"));
const settings=JSON.parse(read("deploy.settings.json"));
const prepare=read("scripts/prepare-cloudflare.mjs");
const verify=read("scripts/verify-deployment.mjs");
const errors=[];
const need=(text,items,label)=>{for(const item of items)if(!text.includes(item))errors.push(`${label} missing ${item}`)};

for(const fn of ["finishSetup","applyHome","setTime","setDay","openMorning","openAlcohol","openSmoking","generateCandidates","saveState","checkServerSync","pushServerState","loadServerState","applySceneAssets","fetchRiskProfile","recordHabitSignal","setupPWAInstall","resetAll","avatarTap","petTap","plantTap","previewLevel"]){if(!html.includes(`function ${fn}(`)&&!html.includes(`async function ${fn}(`))errors.push(`missing function ${fn}`)}
need(worker,["/api/health","/api/avatar/generate","/api/avatar/save","/api/state","/api/event","/api/signal","/api/risk-profile","crypto.subtle.digest","env.DB","env.AVATAR_ASSETS","handleLifeRoute","handleCinemaBackgroundRoute","CinemaBatchWorkflow","AI_TIMEOUT_MS"],"worker");
need(life,["/api/life/summary","/api/life/profile","/api/life/daily","/api/life/smoking","/api/life/condition","/api/life/message","/api/life/reset","handleVisualRoute","resetSetup","resetFull","DELETE FROM clear_messages","DELETE FROM life_daily","DELETE FROM life_profiles","DELETE FROM habit_signals","DELETE FROM app_events","DELETE FROM avatars","DELETE FROM app_state","DELETE FROM device_auth","AVATAR_ASSETS.delete"],"life");
need(visual,["VISUAL_VERSION=\"v26-hybrid3070\"","MOTION_VERSION=\"v26-natural-motion\"","visual-v26/hybrid3070/","HYBRID_RULE","30-real-70-animation","/api/avatar/generate-v17","/api/avatar/hybrid-current","/api/avatar/hybrid/file","/api/avatar/pose","/api/avatar/pose/file","/api/visual/file","/api/visual/ensure","/api/motion/status","/api/motion/generate","/api/motion/file","minimax/hailuo-2.3-fast","walk-sit","stand-walk","pet-touch","window-look","No foot sliding","confirm_cost!==true","AVATAR_ASSETS.put"],"V26 visual/motion server");
if(visual.includes('PREFIX="visual-v17/shared/"'))errors.push("legacy visual-v17 cache prefix returned");
if(visual.includes('"Create a photorealistic full-body lifestyle avatar'))errors.push("legacy photorealistic avatar prompt returned");
if(visual.includes('"Photorealistic premium pet portrait'))errors.push("legacy photorealistic pet prompt returned");
need(avatarRuntime,["progressiveGenerate","fetchOneAvatar","AbortController","85000","/api/avatar/generate-v17","30:70 애니영화형","loadVisual17","loadMotion26","motion-runtime-v26.js?v=26"],"avatar bridge");
need(visualRuntime,["cutout","borderStats","alphaAudit","unsafe cutout","ensureAsset","enhanceAvatar","enhanceRoom","enhancePet","applyVisual","visual17Cutout=cutout","visual17GetMasterCutout","lastAvatarCutout","lastPetCutout"],"safe visual runtime");
need(poseRuntime,["POSES","ensurePose","/api/avatar/pose","/api/avatar/pose/file","poseV20","nextPose","restoreMaster","preload","visual integrity engine not ready","visual17RestoreMaster","visual17GetMasterCutout"],"pose runtime");
if(poseRuntime.includes("img.src=selectedAvatar"))errors.push("pose runtime must never restore raw rectangular avatar source");
need(motionRuntime,["v26-natural-motion","motion26Stage","ambient","walk-sit","stand-walk","pet-touch","window-look","stretch","startAmbient","playOneShot","loadHybrid","/api/avatar/hybrid-current","/api/motion/status","/api/motion/file","/api/motion/generate","confirm_cost:true"],"V26 motion runtime");
need(runtime,["실사용 엔진","맑은 나의 메시지","syncDaily","syncSmoking","syncCondition","riskTick"],"runtime");
need(resetRuntime,["setupReset","fullReset","stopSaving","/api/life/reset","localStorage.removeItem","caches.keys()","window.resetAll=setupReset","window.__resetLock","loadP2Continuity","continuity-runtime-v22.js","p2-continuity"],"reset runtime");
need(roomRuntime,["v19Sun","v19Wind","v19Leaves","moveActor","poseActor","movePet","swayPlant","roomTap","previewLevel","navigator.share","roomV19Audit","refreshActual","applyGrowth","오늘 기록 전"],"room runtime");
need(coreRuntime,["p2CoreV21","riskState","maybeNotify","/api/life/summary","/api/risk-profile"],"core runtime");
need(continuityRuntime,["p2ContinuityV22","continuity-v22","seedHidden","installRewardGuards","syncOverallResult","hiddenSource","smokePoints","conditionRewarded","timerRewards"],"continuity runtime");
need(cinema,["/api/cinema/status","/api/cinema/generate","/api/cinema/file"],"cinema server");
need(cinemaRuntime,["combinations:27","clipSlots:9","URL.createObjectURL","playAction"],"cinema runtime");
need(cinemaBackground,["/api/cinema/batch/start","/api/cinema/batch/status","/api/cinema/batch/public","WorkflowEntrypoint","CinemaBatchWorkflow","step.do","confirm_cost!==true","successRetention"],"cinema background");
need(cinemaBackgroundClient,["myroomCinemaV23BackgroundJob","/api/cinema/batch/start","/api/cinema/batch/status","화면을 닫아도 계속됩니다","stopImmediatePropagation"],"cinema background client");
for(const t of ["app_state","app_events","avatars"])if(!sql1.includes(`CREATE TABLE IF NOT EXISTS ${t}`))errors.push(`missing table ${t}`);
for(const t of ["device_auth","habit_signals"])if(!sql2.includes(`CREATE TABLE IF NOT EXISTS ${t}`))errors.push(`missing table ${t}`);
for(const t of ["life_profiles","life_daily","clear_messages"])if(!sql3.includes(`CREATE TABLE IF NOT EXISTS ${t}`))errors.push(`missing table ${t}`);
if(manifest.display!=="standalone")errors.push("PWA manifest invalid");
need(sw,["my-life-room-v26-shell","hybrid-30-real-70-animation-v26","v26-natural-motion","/motion-runtime-v26.js","/avatar-runtime-v15.js","/visual-runtime-v17.js","/room-experience-v25.js"],"service worker V26 cache");
const requiredFiles=["deploy.settings.json","scripts/prepare-cloudflare.mjs","scripts/verify-deployment.mjs","scripts/visual-hotfix-selfcheck.mjs","scripts/motion-v26-selfcheck.mjs","src/life-engine.js","src/visual-engine.js","src/cinema-engine.js","src/cinema-background.js","public/runtime-v14.js","public/avatar-runtime-v15.js","public/reset-runtime-v16.js","public/visual-runtime-v17.js","public/room-runtime-v19.js","public/pose-runtime-v20.js","public/core-runtime-v21.js","public/continuity-runtime-v22.js","public/cinema-runtime-v23.js","public/cinema-background-v23.js","public/motion-runtime-v26.js","migrations/0003_life_engine.sql"];
for(const f of requiredFiles)if(!fs.existsSync(f))errors.push(`missing deploy file ${f}`);
if(wrangler.name!==settings.worker_name)errors.push(`worker name mismatch: ${wrangler.name} != ${settings.worker_name}`);
if(wrangler.main!=="src/index.js")errors.push("wrangler main entry invalid");
if(wrangler.ai?.binding!==settings.ai_binding)errors.push("Workers AI binding mismatch");
if(wrangler.assets?.binding!=="ASSETS"||wrangler.assets?.directory!=="./public")errors.push("static assets binding invalid");
const workflow=(wrangler.workflows||[]).find(x=>x.binding==="CINEMA_WORKFLOW");if(!workflow||workflow.name!=="my-life-room-cinema-v23"||workflow.class_name!=="CinemaBatchWorkflow")errors.push("Cinema Workflow binding invalid");
need(prepare,["d1\",\"create","r2\",\"bucket\",\"create","d1_databases","r2_buckets","migrations\",\"apply","wrangler.production.jsonc"],"prepare script");
need(verify,["/api/health","/api/life/reset","scope:\"setup\"","scope:\"full\"","/api/avatar/save","/api/avatar/generate-v17","/api/visual/ensure","r2Deleted","DEPLOYMENT VERIFIED"],"verify script");
if(!cinemaBackground.includes('response_format:{type:"json_schema",json_schema:VISUAL_QC_SCHEMA}'))errors.push("Cinema visual QC must use Workers AI direct json_schema shape");
if(!cinemaBackground.includes('response_format:{type:"json_schema",json_schema:MOTION_QC_SCHEMA}'))errors.push("Cinema motion QC must use Workers AI direct json_schema shape");
if(errors.length){console.error(errors.join("\n"));process.exit(1)}
console.log("P2 V26 preflight passed: life engine + 30/70 hybrid visuals + natural motion + Cinema + deployment bindings");
