const CINEMA_VERSION="v26-hybrid3070-motion";
const FRAME_MODEL="@cf/black-forest-labs/flux-2-klein-4b";
const VIDEO_MODEL="minimax/hailuo-2.3-fast";
const VIDEO_DURATION=6;
const BASE_SLOTS=["base-morning","base-evening","base-night"];
const STATE_SLOTS=["state-success","state-steady","state-recovery"];
const ACTION_SLOTS=["action-avatar","action-pet","action-room"];
const MOTION_SLOTS=["motion-idle","motion-walk","motion-sit-down","motion-sit-idle","motion-stand-up","motion-pet-touch"];
const SLOTS=[...BASE_SLOTS,...STATE_SLOTS,...ACTION_SLOTS,...MOTION_SLOTS];
const BASES=["morning","evening","night"];
const STATES=["success","steady","recovery"];
const ACTIONS=["avatar","pet","room"];
const STYLE_RULE="Premium contemporary animated feature-film look: approximately 70 percent refined animation illustration and 30 percent realistic physical detail. The entire person, companion pet and room must belong to one coherent animated-film world. Preserve believable adult anatomy, body weight, perspective, fabric, fur, wood, contact shadows and cinematic light as the 30 percent realistic layer, while the overall image clearly reads as a polished animation movie frame rather than live-action photography. Avoid plastic 3D toy style, game-avatar stiffness, chibi proportions, flat web cartoon and photorealistic live-action.";
function safeSlot(v){const s=String(v||"").trim();return SLOTS.includes(s)?s:null}
function safeChoice(v,allowed,fallback){const s=String(v||"").trim();return allowed.includes(s)?s:fallback}
function avatarPrefix(key){const s=String(key||"");return s.endsWith("master.jpg")?s.slice(0,-"master.jpg".length):s.replace(/[^/]+$/,"")}
async function latestAvatar(env,deviceId){return await env.DB.prepare("SELECT r2_key,style FROM avatars WHERE device_id=?1 ORDER BY id DESC LIMIT 1").bind(deviceId).first()}
function frameKey(row,slot){return `${avatarPrefix(row.r2_key)}cinema-v26/hybrid3070/${slot}.jpg`}
function videoKey(row,slot){return `${avatarPrefix(row.r2_key)}cinema-v26/hybrid3070/${slot}.mp4`}
function fileUrl(slot,type="video"){return `/api/cinema/file?slot=${encodeURIComponent(slot)}&type=${type}`}
function bytesToBase64(bytes){let out="";const step=0x8000;for(let i=0;i<bytes.length;i+=step)out+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(out)}
async function withTimeout(promise,ms,label){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} timed out`)),ms)});try{return await Promise.race([promise,timeout])}finally{clearTimeout(timer)}}
function petDescriptor(kind,mode){if(kind==="cat")return mode==="집사취급형"?"one elegant silver-tabby companion cat, composed and slightly aloof":"one affectionate silver-tabby companion cat with warm curious eyes";return mode==="듬직이형"?"one calm loyal medium-small warm-brown companion dog":"one bright friendly small warm-brown companion dog"}
function roomDescriptor(style){return style==="modern"?"refined contemporary Korean apartment living room with pale stone, oak and linen":style==="cozy"?"cozy premium Korean apartment living room with warm linen, oak and soft natural textures":"warm modern Korean apartment living room with cream fabric, natural oak and tasteful plants"}
function framePrompt(slot,{roomStyle,petKind,petMode}){
 const room=roomDescriptor(roomStyle),pet=petDescriptor(petKind,petMode);
 const shared=[STYLE_RULE,"Use input image 0 as the exact identity reference for the same adult person.","Preserve recognizable face, age, hairstyle, skin tone, body build and clothing identity while translating the whole scene into the same 70/30 animation-film style.",`Place exactly one adult person and ${pet} together inside a ${room}.`,"Person, pet, furniture and environment must be painted/rendered in one consistent visual language with matching light direction, contact shadows, scale and depth.","Stable cinematic camera at human eye level, natural perspective, believable furniture scale and enough clear floor space for walking and sitting motion.","No second person, no second animal, no collage, no floating subject, no studio backdrop, no text, no logo, no UI, no live-action photographic look."];
 const scene={
  "base-morning":"Wide establishing frame. Early morning sunlight through curtains. The person stands naturally a few steps from the sofa; the pet rests nearby. Calm breathing-space around the body for subtle ambient motion.",
  "base-evening":"Wide establishing frame. Warm blue-hour evening and practical lamps. The person has just returned home and stands near the sofa while the pet stays close.",
  "base-night":"Wide establishing frame. Calm late-night room with warm lamps and deep blue city light outside. The person winds down quietly near the sofa with the pet nearby.",
  "state-success":"Medium-wide frame. The person looks quietly proud and relieved after keeping a healthy promise; shoulders relaxed, pet calm nearby, room slightly brighter and more alive.",
  "state-steady":"Medium-wide frame. A normal steady day with relaxed breathing, neutral warm expression, tidy room and calm pet.",
  "state-recovery":"Medium-wide frame. Gentle recovery mood after a difficult day. The person is calm with water or tea, no shame, pet quietly close, supportive light.",
  "action-avatar":"Medium-wide interaction frame. The person has room to shift weight, turn naturally and make one small stretch while the pet remains calm.",
  "action-pet":"Medium-low interaction frame. The pet is within comfortable reach of the person for one natural affectionate touch without awkward bending.",
  "action-room":"Wide room-reaction frame. Curtain and plant are visible so a breeze can move them while the person and pet react subtly.",
  "motion-idle":"Full-body wide frame. The person stands comfortably with neutral balance, feet naturally planted, shoulders soft, arms relaxed, pet nearby. This is the neutral anchor pose for ambient life motion.",
  "motion-walk":"Full-body wide frame with the person at one side of the room, standing upright and ready to walk three to four natural steps toward the sofa. Clear unobstructed path visible from feet to sofa.",
  "motion-sit-down":"Full-body wide frame with the person standing immediately in front of the sofa, body aligned to sit. Knees, hips, feet and sofa seat fully visible. Pet stays safely to one side.",
  "motion-sit-idle":"Medium-wide seated frame. The person is already seated naturally on the sofa with feet grounded, knees relaxed, hands resting comfortably, spine supported and pet nearby.",
  "motion-stand-up":"Full-body wide frame. The person starts seated naturally near the front edge of the sofa with feet placed under the knees, ready to lean forward and stand. Entire body and feet visible.",
  "motion-pet-touch":"Medium-wide frame. The person and pet are positioned close enough for a natural gentle petting interaction with believable reach and no extreme bending. Hands and pet body clearly visible."
 }[slot];
 return [...shared,scene].join(" ")
}
function motionPrompt(slot){
 const common=`Maintain the exact same adult identity, age, face, hairstyle, clothing, companion pet, room geometry, furniture placement, camera position and 70/30 animation-film visual style from the first frame. Motion must feel like a high-quality animated feature film: continuous weight transfer, anticipation before movement, natural acceleration and deceleration, coordinated shoulders-hips-knees-elbows, subtle secondary motion in clothing and hair, stable anatomy and consistent proportions. No robotic joint snapping, no puppet stiffness, no sliding feet, no morphing, no extra limbs, no extra people or animals, no camera cut, no room change, no text. Keep physically believable contact with floor and sofa.`;
 const motion={
  "base-morning":"Very calm ambient loop. Natural breathing, one blink, tiny weight shift, subtle curtain motion and soft sunlight drift. Pet makes one small head movement. End almost exactly at the starting pose for a seamless loop.",
  "base-evening":"Quiet blue-hour ambient loop. The person breathes and makes one subtle posture adjustment, pet glances up once, lamp glow and curtain move slightly. End close to the starting pose.",
  "base-night":"Quiet night ambient loop. The person relaxes shoulders, blinks and breathes slowly, pet settles, outside city glow remains stable. End close to the starting pose.",
  "state-success":"A small genuine smile appears, shoulders release tension, chest opens slightly with relief, pet responds warmly with one subtle movement. Restrained natural emotion, no celebration gesture.",
  "state-steady":"One normal breath and a small balanced posture adjustment. Pet remains calm. Everyday natural motion only.",
  "state-recovery":"The person takes a slow calming breath, gaze lowers briefly, then returns to neutral. Pet stays quietly supportive. Gentle restrained emotion.",
  "action-avatar":"The person shifts weight through hips and feet, turns slightly toward the window, opens shoulders in a small stretch, then settles back naturally. Arms, torso, head and knees move as one connected body.",
  "action-pet":"The pet takes a few natural steps toward the person. The person responds with a small weight shift and gentle reach, gives one brief affectionate touch, then both settle naturally.",
  "action-room":"A soft breeze moves curtain and plant leaves. The person notices with a subtle head and eye turn; the pet gives a small natural reaction; everything settles again.",
  "motion-idle":"Feature-film quality idle performance. Subtle breathing expands ribcage and shoulders, one or two natural blinks, tiny head movement, slight hand and finger settling, gentle weight shift between feet, minimal cloth and hair follow-through. No repeated mechanical bobbing. End very close to start for looping.",
  "motion-walk":"The person initiates walking with a small anticipatory weight shift, then takes three to four believable steps toward the sofa. Heel-to-toe foot contact, knees flex naturally, hips rotate subtly, opposite arm swings gently, torso and head remain balanced, clothing and hair follow with slight inertia. Slow naturally near the sofa and finish standing stable without foot sliding.",
  "motion-sit-down":"From standing in front of the sofa, the person glances slightly downward, shifts hips back, bends knees and ankles, inclines torso forward just enough for balance, then lowers body weight smoothly until the hips contact the sofa. Hands and arms counterbalance naturally. After contact, the pelvis settles, feet adjust slightly and the upper body relaxes into a comfortable seated posture. No sudden pose swap.",
  "motion-sit-idle":"Already seated. Natural slow breathing, tiny posture settling through pelvis and spine, one relaxed hand adjustment on thigh or sofa, one blink and subtle head turn. Feet remain grounded and knees stable. End close to start for looping.",
  "motion-stand-up":"From seated, the person first places feet securely, leans torso forward, shifts center of mass over the feet, presses through legs, extends knees and hips smoothly, lets arms counterbalance, then rises fully to a stable upright stance. Small final posture correction and natural breath. No teleporting or joint snapping.",
  "motion-pet-touch":"The person notices the pet, shifts weight and lowers the upper body only as much as needed, reaches with one relaxed hand, makes gentle contact and strokes the pet once or twice. The pet reacts with subtle head/body movement. Shoulder, elbow, wrist and fingers coordinate naturally; spine and knees compensate for balance. Return smoothly to a relaxed position."
 }[slot];
 return `${motion} ${common}`
}
async function generateFrame(env,sourceBlob,prompt,seed){const form=new FormData();form.append("prompt",prompt);form.append("input_image_0",sourceBlob,"identity.jpg");form.append("width","896");form.append("height","1024");form.append("guidance","3.8");form.append("seed",String(seed));const serialized=new Response(form);const result=await withTimeout(env.AI.run(FRAME_MODEL,{multipart:{body:serialized.body,contentType:serialized.headers.get("content-type")}}),90000,"Cinema frame generation");if(!result||typeof result.image!=="string"||result.image.length<1000)throw new Error("Cinema frame model did not return an image");const raw=atob(result.image),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
async function generateVideo(env,frameBytes,prompt){const firstFrame=`data:image/jpeg;base64,${bytesToBase64(frameBytes)}`;const result=await withTimeout(env.AI.run(VIDEO_MODEL,{prompt,duration:VIDEO_DURATION,fast_pretreatment:true,first_frame_image:firstFrame,prompt_optimizer:true,resolution:"768P"}),180000,"Cinema video generation");const url=result?.result?.video||result?.video;if(!url)throw new Error(`Cinema video model returned no video (${result?.state||result?.result?.status||"unknown"})`);const r=await fetch(url);if(!r.ok)throw new Error(`Generated video download failed: ${r.status}`);const type=r.headers.get("content-type")||"video/mp4",buffer=await r.arrayBuffer(),bytes=new Uint8Array(buffer);if(!type.includes("video")&&!url.includes(".mp4"))throw new Error("Generated asset is not a video");if(bytes.byteLength<50000||bytes.byteLength>60000000)throw new Error(`Generated video size is suspicious: ${bytes.byteLength}`);return {bytes,type}}
async function ensureFrame(env,row,slot,opts,force=false){const key=frameKey(row,slot),head=await env.AVATAR_ASSETS.head(key);if(head&&!force){const obj=await env.AVATAR_ASSETS.get(key);return {key,bytes:new Uint8Array(await obj.arrayBuffer()),cached:true}}const src=await env.AVATAR_ASSETS.get(row.r2_key);if(!src)throw new Error("Saved avatar master was not found");const bytes=await generateFrame(env,await src.blob(),framePrompt(slot,opts),Math.floor(Math.random()*1000000000));await env.AVATAR_ASSETS.put(key,bytes,{httpMetadata:{contentType:"image/jpeg",cacheControl:"private, max-age=31536000"},customMetadata:{engine:CINEMA_VERSION,slot,role:"cinema-frame",styleBlend:"30-real-70-animation"}});return {key,bytes,cached:false}}
async function status(env,row){const slots=[];for(const slot of SLOTS){const [frame,video]=await Promise.all([env.AVATAR_ASSETS.head(frameKey(row,slot)),env.AVATAR_ASSETS.head(videoKey(row,slot))]);slots.push({slot,frame:Boolean(frame),video:Boolean(video),url:video?fileUrl(slot):null,group:MOTION_SLOTS.includes(slot)?"motion":BASE_SLOTS.includes(slot)?"base":STATE_SLOTS.includes(slot)?"state":"action"})}return slots}
async function serveFile(request,env,row,slot,type){const key=type==="frame"?frameKey(row,slot):videoKey(row,slot),obj=await env.AVATAR_ASSETS.get(key);if(!obj)return new Response("Not found",{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set("cache-control","private, max-age=3600");headers.set("x-cinema-engine",CINEMA_VERSION);headers.set("x-style-blend","30-real-70-animation");if(!headers.get("content-type"))headers.set("content-type",type==="frame"?"image/jpeg":"video/mp4");return new Response(obj.body,{headers})}
export async function handleCinemaRoute(request,env,ensureAuth,json){
 const url=new URL(request.url);if(!url.pathname.startsWith("/api/cinema/"))return null;
 if(!env.DB||!env.AVATAR_ASSETS)return json({ok:false,error:"Cinema Room requires D1 and R2"},503);
 const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;const row=await latestAvatar(env,auth.deviceId);if(!row?.r2_key)return json({ok:false,error:"본캐를 먼저 만들어 저장해야 합니다."},409);
 if(url.pathname==="/api/cinema/status"&&request.method==="GET"){const slots=await status(env,row);const motionReady=slots.filter(x=>x.group==="motion"&&x.video).length;return json({ok:true,engine:CINEMA_VERSION,styleBlend:"30-real-70-animation",frameModel:FRAME_MODEL,videoModel:VIDEO_MODEL,pilot:{bases:BASES,states:STATES,actions:ACTIONS,legacyClipSlots:BASE_SLOTS.length+STATE_SLOTS.length+ACTION_SLOTS.length},motion:{slots:MOTION_SLOTS,ready:motionReady,total:MOTION_SLOTS.length,sequence:["motion-walk","motion-sit-down","motion-sit-idle","motion-stand-up"]},slots,ready:slots.filter(x=>x.video).length,total:SLOTS.length})}
 if(url.pathname==="/api/cinema/file"&&request.method==="GET"){const slot=safeSlot(url.searchParams.get("slot")),type=url.searchParams.get("type")==="frame"?"frame":"video";if(!slot)return new Response("Not found",{status:404});return serveFile(request,env,row,slot,type)}
 if(url.pathname==="/api/cinema/generate"&&request.method==="POST"){
  if(!env.AI)return json({ok:false,error:"Workers AI binding is required"},503);const b=await request.json().catch(()=>({})),slot=safeSlot(b.slot);if(!slot)return json({ok:false,error:"Invalid cinema slot"},400);if(b.confirm_cost!==true)return json({ok:false,error:"AI video generation may incur Cloudflare charges. Explicit confirm_cost=true is required."},402);
  const opts={roomStyle:safeChoice(b.roomStyle,["warm","modern","cozy"],"warm"),petKind:safeChoice(b.petKind,["dog","cat"],"dog"),petMode:String(b.petMode||"댕댕이형").slice(0,30),force:Boolean(b.force)};
  try{const vKey=videoKey(row,slot),existing=await env.AVATAR_ASSETS.head(vKey);if(existing&&!opts.force)return json({ok:true,engine:CINEMA_VERSION,styleBlend:"30-real-70-animation",slot,cached:true,url:fileUrl(slot)});const frame=await ensureFrame(env,row,slot,opts,opts.force),video=await generateVideo(env,frame.bytes,motionPrompt(slot));await env.AVATAR_ASSETS.put(vKey,video.bytes,{httpMetadata:{contentType:"video/mp4",cacheControl:"private, max-age=31536000"},customMetadata:{engine:CINEMA_VERSION,model:VIDEO_MODEL,slot,role:"cinema-video",styleBlend:"30-real-70-animation",duration:String(VIDEO_DURATION),bytes:String(video.bytes.byteLength)}});return json({ok:true,engine:CINEMA_VERSION,styleBlend:"30-real-70-animation",slot,cached:false,frameCached:frame.cached,url:fileUrl(slot),duration:VIDEO_DURATION,bytes:video.bytes.byteLength})}catch(error){return json({ok:false,error:error?.message||"Cinema Room generation failed",slot},500)}
 }
 return json({ok:false,error:"Not found"},404)
}
export const CINEMA_INFO={version:CINEMA_VERSION,frameModel:FRAME_MODEL,videoModel:VIDEO_MODEL,slots:SLOTS,motionSlots:MOTION_SLOTS,bases:BASES,states:STATES,actions:ACTIONS};
