const P3_VERSION="p3-p2-control-v1";
const EXPECTED_SCENE_SLOTS=50;
const MASTER_FRAME_TARGET=8;
const SAFE_ID=/^[A-Za-z0-9._:-]{1,128}$/;
const ASSET_KINDS=new Set(["master_frame","scene_video","room_reference","avatar_reference","pet_reference","other"]);
const EVIDENCE_LEVELS=new Set(["reference","r2-verified"]);
const STATUSES=new Set(["active","approved","rejected","archived"]);

function safeId(v){const s=String(v||"").trim();return SAFE_ID.test(s)?s:null}
function safeText(v,max=240){const s=String(v||"").trim();return s?s.slice(0,max):null}
async function logAudit(env,deviceId,eventType,payload={}){try{await env.DB?.prepare("INSERT INTO p3_audit_log (device_id,event_type,payload_json) VALUES (?1,?2,?3)").bind(deviceId||null,eventType,JSON.stringify(payload)).run()}catch{}}
async function countR2(env,prefix){if(!env.AVATAR_ASSETS)return {ok:false,count:0,error:"R2 binding missing"};let count=0,cursor=undefined,guard=0;try{do{const out=await env.AVATAR_ASSETS.list({prefix,cursor,limit:1000});count+=(out.objects||[]).length;cursor=out.truncated?out.cursor:undefined;guard++}while(cursor&&guard<25);return {ok:true,count,truncated:Boolean(cursor)}}catch(error){return {ok:false,count:0,error:error?.message||"R2 list failed"}}}
async function sceneStats(env,deviceId){const row=await env.DB.prepare("SELECT COUNT(*) total, SUM(CASE WHEN qc_status='ready' THEN 1 ELSE 0 END) ready, SUM(CASE WHEN qc_status='draft' THEN 1 ELSE 0 END) draft, SUM(CASE WHEN qc_status='rejected' THEN 1 ELSE 0 END) rejected, COALESCE(SUM(size_bytes),0) bytes FROM scene_assets WHERE device_id=?1").bind(deviceId).first();return {total:Number(row?.total||0),ready:Number(row?.ready||0),draft:Number(row?.draft||0),rejected:Number(row?.rejected||0),bytes:Number(row?.bytes||0)}}
async function registryStats(env,deviceId){const rows=await env.DB.prepare("SELECT asset_kind,evidence_level,status,COUNT(*) count FROM p3_asset_registry WHERE device_id=?1 GROUP BY asset_kind,evidence_level,status").bind(deviceId).all();const items=rows.results||[];const master=items.filter(x=>x.asset_kind==="master_frame"&&["active","approved"].includes(x.status));return {rows:items.map(x=>({...x,count:Number(x.count||0)})),masterFrames:{target:MASTER_FRAME_TARGET,verified:master.filter(x=>x.evidence_level==="r2-verified").reduce((n,x)=>n+Number(x.count||0),0),referenced:master.filter(x=>x.evidence_level==="reference").reduce((n,x)=>n+Number(x.count||0),0)}}}

async function userStatus(request,env,ensureAuth,json){if(!env.DB)return json({ok:false,error:"D1 binding is not connected."},503);const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;let scenes,registry;try{scenes=await sceneStats(env,auth.deviceId);registry=await registryStats(env,auth.deviceId)}catch(error){return json({ok:false,error:"P3 tables are not ready",detail:error?.message||String(error)},503)}const r2Scenes=await countR2(env,`scene-library/${auth.deviceId}/`);const warnings=[];if(r2Scenes.ok&&r2Scenes.count!==scenes.total)warnings.push(`D1 scene rows (${scenes.total}) and R2 scene files (${r2Scenes.count}) differ.`);if(registry.masterFrames.verified+registry.masterFrames.referenced<MASTER_FRAME_TARGET)warnings.push(`P3 master-frame registry is ${registry.masterFrames.verified+registry.masterFrames.referenced}/${MASTER_FRAME_TARGET}.`);const result={ok:true,p3:true,version:P3_VERSION,freeOnly:true,truthPolicy:{noGuess:true,unverifiedValuesAreSeparated:true},bindings:{d1:Boolean(env.DB),r2:Boolean(env.AVATAR_ASSETS),ai:Boolean(env.AI)},sceneLibrary:{expectedSlots:EXPECTED_SCENE_SLOTS,d1:scenes,r2Files:r2Scenes},masterFrames:registry.masterFrames,registry:registry.rows,warnings,checkedAt:new Date().toISOString()};await logAudit(env,auth.deviceId,"status-check",{sceneRows:scenes.total,r2SceneFiles:r2Scenes.count,masterFrames:registry.masterFrames});return json(result)}

async function preflight(request,env,ensureAuth,json){if(!env.DB)return json({ok:false,pass:false,error:"D1 binding is not connected."},503);const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;const checks={d1:Boolean(env.DB),r2:Boolean(env.AVATAR_ASSETS),ai:Boolean(env.AI),sceneTable:false,p3RegistryTable:false,r2Readable:false};try{await env.DB.prepare("SELECT 1 FROM scene_assets LIMIT 1").first();checks.sceneTable=true}catch{}try{await env.DB.prepare("SELECT 1 FROM p3_asset_registry LIMIT 1").first();checks.p3RegistryTable=true}catch{}const r2=await countR2(env,`scene-library/${auth.deviceId}/`);checks.r2Readable=r2.ok;const pass=Object.values(checks).every(Boolean);await logAudit(env,auth.deviceId,"preflight",{pass,checks});return json({ok:true,pass,p3:true,version:P3_VERSION,checks,checkedAt:new Date().toISOString()})}

async function listRegistry(request,env,ensureAuth,json){if(!env.DB)return json({ok:false,error:"D1 binding is not connected."},503);const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;const rows=await env.DB.prepare("SELECT asset_kind,asset_id,label,storage_ref,evidence_level,status,created_at,updated_at FROM p3_asset_registry WHERE device_id=?1 ORDER BY updated_at DESC").bind(auth.deviceId).all();return json({ok:true,assets:rows.results||[]})}

async function registerAsset(request,env,ensureAuth,json){if(!env.DB)return json({ok:false,error:"D1 binding is not connected."},503);const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;const body=await request.json().catch(()=>null),assetKind=String(body?.asset_kind||"").trim(),assetId=safeId(body?.asset_id),label=safeText(body?.label),storageRef=safeText(body?.storage_ref,512),evidence=String(body?.evidence_level||"reference").trim(),status=String(body?.status||"active").trim();if(!ASSET_KINDS.has(assetKind)||!assetId||!EVIDENCE_LEVELS.has(evidence)||!STATUSES.has(status))return json({ok:false,error:"Invalid P3 asset payload"},400);if(evidence==="r2-verified"){if(!env.AVATAR_ASSETS)return json({ok:false,error:"R2 binding is not connected."},503);if(!storageRef)return json({ok:false,error:"storage_ref is required for r2-verified evidence"},400);const head=await env.AVATAR_ASSETS.head(storageRef);if(!head)return json({ok:false,error:"R2 object does not exist; refusing verified registration"},409)}await env.DB.prepare("INSERT INTO p3_asset_registry (device_id,asset_kind,asset_id,label,storage_ref,evidence_level,status,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,datetime('now')) ON CONFLICT(device_id,asset_kind,asset_id) DO UPDATE SET label=excluded.label,storage_ref=excluded.storage_ref,evidence_level=excluded.evidence_level,status=excluded.status,updated_at=datetime('now')").bind(auth.deviceId,assetKind,assetId,label,storageRef,evidence,status).run();await logAudit(env,auth.deviceId,"asset-register",{assetKind,assetId,evidence,status});return json({ok:true,asset_kind:assetKind,asset_id:assetId,evidence_level:evidence,status})}

async function deleteAsset(request,env,ensureAuth,json){if(!env.DB)return json({ok:false,error:"D1 binding is not connected."},503);const auth=await ensureAuth(request,env,true);if(!auth.ok)return auth.response;const url=new URL(request.url),assetKind=String(url.searchParams.get("asset_kind")||"").trim(),assetId=safeId(url.searchParams.get("asset_id"));if(!ASSET_KINDS.has(assetKind)||!assetId)return json({ok:false,error:"Invalid P3 asset key"},400);const out=await env.DB.prepare("DELETE FROM p3_asset_registry WHERE device_id=?1 AND asset_kind=?2 AND asset_id=?3").bind(auth.deviceId,assetKind,assetId).run();await logAudit(env,auth.deviceId,"asset-delete",{assetKind,assetId});return json({ok:true,deleted:Number(out.meta?.changes||0)>0,asset_kind:assetKind,asset_id:assetId})}

export async function handleP3ControlRoute(request,env,ensureAuth,json){const url=new URL(request.url),p=url.pathname;if(p==="/api/p3/health"&&request.method==="GET")return json({ok:true,p3:true,version:P3_VERSION,freeOnly:true,expectedSceneSlots:EXPECTED_SCENE_SLOTS,masterFrameTarget:MASTER_FRAME_TARGET,bindings:{d1:Boolean(env.DB),r2:Boolean(env.AVATAR_ASSETS),ai:Boolean(env.AI)}});if(p==="/api/p3/status"&&request.method==="GET")return userStatus(request,env,ensureAuth,json);if(p==="/api/p3/preflight"&&(request.method==="GET"||request.method==="POST"))return preflight(request,env,ensureAuth,json);if(p==="/api/p3/assets"&&request.method==="GET")return listRegistry(request,env,ensureAuth,json);if(p==="/api/p3/assets"&&request.method==="POST")return registerAsset(request,env,ensureAuth,json);if(p==="/api/p3/assets"&&request.method==="DELETE")return deleteAsset(request,env,ensureAuth,json);return null}

export const P3_CONTROL_INFO={version:P3_VERSION,expectedSceneSlots:EXPECTED_SCENE_SLOTS,masterFrameTarget:MASTER_FRAME_TARGET,freeOnly:true};
